add method to manage alias
gravitee-io/gravitee-common-elasticsearch pull request #173
Opened 2022-05-13 17:46 UTC by phiz71

**Issue**

https://github.com/gravitee-io/issues/issues/7110

**Description**

add method to manage alias

2022-05-16 11:21 UTC, brasseld requested changes

2022-05-16 11:21 UTC, brasseld commented on src/main/java/io/gravitee/elasticsearch/client/Client.java
> +    Single<JsonNode> getAlias(String aliasName);
Should return a Maybe to differentiate technical issue from no alias found.

2022-05-16 11:23 UTC, brasseld commented on src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
> +            "{\n" +
That hurts my 👀

2022-05-17 13:38 UTC, gaetanmaisse approved these changes

2022-05-17 13:38 UTC, merged

2022-05-17 13:44 UTC, graviteeio commented
:tada: This PR is included in version 3.8.5 :tada:

The release is available on:
- `3.8.5`
- [GitHub release](https://github.com/gravitee-io/gravitee-common-elasticsearch/releases/tag/3.8.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-17 18:51 UTC, graviteeio commented
:tada: This PR is included in version 3.12.1 :tada:

The release is available on:
- `3.12.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-common-elasticsearch/releases/tag/3.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-17 20:57 UTC, graviteeio commented
:tada: This PR is included in version 3.12.1 :tada:

The release is available on [GitHub release](https://github.com/gravitee-io/gravitee-common-elasticsearch/releases/tag/3.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: